version: '3.8'
services:
  app:
    image: innoscripta-test-case
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3001:3000"